modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Friendly-Fire/issues"

[[mods]]
modId="cursed"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.cursed]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cursed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"