modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Cursed/issues"
license="LGPL v2.1"
logoFile="mod_logo.png"
logoBlur=false

[[mods]]
modId="cursed"
updateJSONURL="https://updates.blamejared.com/get?n=cursed&gv=1.16.5"
version="${version}"
displayName="${modName}"
displayURL="${modHomepage}"
credits="${modCredits}"
authors="${modAuthor}"
description='''
${modDescription}
'''
itemIcon="minecraft:enchanted_book"

[[dependencies.cursed]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cursed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.cursed]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"