modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Friendly-Fire/issues"

[[mods]]
modId="cursed"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.cursed]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.18,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cursed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.cursed]]
    modId="bookshelf"
    mandatory=true
    versionRange="[5.3,)"
    ordering="AFTER"
    side="BOTH"