modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Cursed/issues"
license="LGPL v2.1"

[[mods]]
modId="cursed"
updateJSONURL="https://updates.blamejared.com/get?n=cursed&gv=1.16.3"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.cursed]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cursed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.cursed]]
    modId="bookshelf"
    mandatory=true
    versionRange="[8,)"
    ordering="AFTER"
    side="BOTH"